# Generated by Django 4.1.5 on 2023-01-19 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fjc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fjc.accessories'),
        ),
    ]
