# Generated by Django 4.1.5 on 2023-02-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fjc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionimage',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
