# Generated by Django 4.1.5 on 2023-02-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fjc', '0002_accessories_views_collection_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='name',
            new_name='title',
        ),
    ]
