# Generated by Django 4.1.5 on 2023-03-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fjc', '0003_rename_name_truck_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='trail_team',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='image',
            field=models.ImageField(null=True, upload_to='picstore/fj/accessories/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(null=True, upload_to='picstore/fj/collection'),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='image',
            field=models.ImageField(null=True, upload_to='picsstore/fj/collection/more'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, upload_to='picstore/fj/truck/'),
        ),
    ]
